language: php
php:
  - 5.6
  - 7.0
  - 7.1

install:
  - composer install --dev --no-interaction --prefer-source

script:
  - vendor/phpunit/phpunit/phpunit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
