language: php
php:
  - 5.6
  - 7.0
  - 7.1

install:
  - php composer.phar install --dev --no-interaction --prefer-source

script:
  - bin/phpunit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
