translation_validator:
    pattern: /validate/{lang}
    defaults: { _controller: translation.validator.controller:validate, validate: 'en'}
translation_validator_lang:
    pattern: /validate/{lang}/{validate}
    defaults: { _controller: translation.validator.controller:validate}
