translation_validator_olympus_origin:
    pattern: /validate/3.0/{origin}
    defaults: { _controller: translation.validator.controller:validate, version: '3.0', upstream: 'en'}
translation_validator_olympus_origin_upstream:
    pattern: /validate/3.0/{origin}/{upstream}
    defaults: { _controller: translation.validator.controller:validate, version: '3.0'}
translation_validator_ascraeus_origin:
    pattern: /validate/3.1/{origin}
    defaults: { _controller: translation.validator.controller:validate, version: '3.1', upstream: 'en'}
translation_validator_ascraeus_origin_upstream:
    pattern: /validate/3.1/{origin}/{upstream}
    defaults: { _controller: translation.validator.controller:validate, version: '3.1'}

translation_validator_legacy:
    pattern: /validate/{origin}
    defaults: { _controller: translation.validator.controller:validate, version: '3.0', upstream: 'en'}
translation_validator_lang_legacy:
    pattern: /validate/{origin}/{upstream}
    defaults: { _controller: translation.validator.controller:validate, version: '3.0'}
