translation_validator:
    pattern: /validate
    defaults: { _controller: translation.validator.controller:validate }
translation_validator_lang:
    pattern: /validate/{lang}/{validate}
    defaults: { _controller: translation.validator.controller:validate, validate: 'en'}
