imports:
#    - { resource: parameters.yml }

parameters:
    translation.validator.package.dir: %core.root_path%store/language-packages/

services:
    translation.validator.controller:
        class: phpbb_ext_official_translationvalidator_controller_validator
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @service_container
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%

    translation.validator:
        class: phpbb_ext_official_translationvalidator_validator
        arguments:
            - @translation.validator.filelist
            - @translation.validator.file
            - @translation.validator.error_collection
            - @user
            - %translation.validator.package.dir%

    translation.validator.error_collection:
        class: phpbb_ext_official_translationvalidator_error_collection
        arguments:

    translation.validator.file:
        class: phpbb_ext_official_translationvalidator_validator_file
        arguments:
            - @translation.validator.key
            - @translation.validator.error_collection
            - @user
            - %translation.validator.package.dir%

    translation.validator.filelist:
        class: phpbb_ext_official_translationvalidator_validator_filelist
        arguments:
            - @translation.validator.error_collection
            - @user
            - %translation.validator.package.dir%

    translation.validator.key:
        class: phpbb_ext_official_translationvalidator_validator_key
        arguments:
            - @translation.validator.error_collection
            - @user
