imports:
#    - { resource: parameters.yml }

services:
    translation.validator.controller:
        class: phpbb_ext_official_translationvalidator_controller_validator
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @service_container
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%

    translation.validator:
        class: phpbb_ext_official_translationvalidator_validator
        arguments:
            - @translation.validator.error_collection
            - @user
            - %core.root_path%store/language-packages/

    translation.validator.error_collection:
        class: phpbb_ext_official_translationvalidator_error_collection
        arguments:
