imports:
#    - { resource: parameters.yml }

parameters:
    translation.validator.package.dir: %core.root_path%store/language-packages/

services:
    translation.validator.controller:
        class: official\translationvalidator\controller\validator
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @service_container
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%

    translation.validator:
        class: official\translationvalidator\validator\validator
        arguments:
            - @translation.validator.filelist
            - @translation.validator.file
            - @translation.validator.message_collection
            - @user
            - %translation.validator.package.dir%

    translation.validator.message_collection:
        class: official\translationvalidator\message_collection
        arguments:

    translation.validator.file:
        class: official\translationvalidator\validator\file
        arguments:
            - @translation.validator.key
            - @translation.validator.message_collection
            - @user
            - %translation.validator.package.dir%

    translation.validator.filelist:
        class: official\translationvalidator\validator\filelist
        arguments:
            - @translation.validator.message_collection
            - @user
            - %translation.validator.package.dir%

    translation.validator.key:
        class: official\translationvalidator\validator\key
        arguments:
            - @translation.validator.message_collection
            - @user
